// lib/mockData.ts

export const MOCK_WORKER = {
  id: "w-001",
  name: "Sameer Shaikh",
  phone: "+91 98765 43210",
  city: "Mumbai",
  zone: "Andheri West",
  platform: "Swiggy",
  avgDailyHours: 9,
  avgDailyEarning: 800,
  riskScore: 0.62,
  memberSince: "Jan 2025",
};

export const MOCK_ACTIVE_POLICY = {
  id: "pol-2024-W12",
  status: "active",
  weekLabel: "Week of Mar 17–23, 2026",
  premium: 64,
  coverageAmount: 640,
  zone: "Andheri West",
  city: "Mumbai",
  multipliers: {
    baseRate: 35,
    zoneMultiplier: 1.40,
    weatherMultiplier: 1.30,
    historyMultiplier: 1.00,
    finalPremium: 63.70,
  },
  purchasedAt: "Mar 17, 2026, 8:02 AM",
};

export const MOCK_CLAIMS = [
  {
    id: "clm-001",
    date: "Mar 18, 2026",
    time: "7:45 PM",
    triggerType: "heavy_rainfall",
    triggerLabel: "Heavy Rainfall",
    zone: "Andheri West",
    city: "Mumbai",
    rainfallValue: "25.4 mm/hr",
    disruptionHours: 4,
    payoutAmount: 320,
    status: "paid",
    fraudScore: 0.08,
    bcsScore: 87,
    bcsTier: 1,
    paidAt: "Mar 18, 2026, 8:01 PM",
    razorpayRef: "pay_RZP9X2K3L",
    policyId: "pol-2024-W12",
  },
  {
    id: "clm-002",
    date: "Mar 12, 2026",
    time: "2:15 PM",
    triggerType: "extreme_heat",
    triggerLabel: "Extreme Heat",
    zone: "Andheri West",
    city: "Mumbai",
    rainfallValue: "45.2°C feels like",
    disruptionHours: 4,
    payoutAmount: 320,
    status: "paid",
    fraudScore: 0.05,
    bcsScore: 92,
    bcsTier: 1,
    paidAt: "Mar 12, 2026, 2:28 PM",
    razorpayRef: "pay_RZP8M1J7P",
    policyId: "pol-2024-W11",
  },
  {
    id: "clm-003",
    date: "Mar 5, 2026",
    time: "11:00 AM",
    triggerType: "flood_alert",
    triggerLabel: "Flood / Red Alert",
    zone: "Andheri West",
    city: "Mumbai",
    rainfallValue: "IMD Red Alert Active",
    disruptionHours: 8,
    payoutAmount: 640,
    status: "paid",
    fraudScore: 0.12,
    bcsScore: 79,
    bcsTier: 1,
    paidAt: "Mar 5, 2026, 11:14 AM",
    razorpayRef: "pay_RZP7N5H2Q",
    policyId: "pol-2024-W10",
  },
  {
    id: "clm-004",
    date: "Feb 27, 2026",
    time: "6:30 PM",
    triggerType: "heavy_rainfall",
    triggerLabel: "Heavy Rainfall",
    zone: "Andheri West",
    city: "Mumbai",
    rainfallValue: "18.1 mm/hr",
    disruptionHours: 4,
    payoutAmount: 320,
    status: "flagged",
    fraudScore: 0.71,
    bcsScore: 34,
    bcsTier: 3,
    flagReasons: ["Cell tower mismatch (Andheri vs Bandra)", "Platform status: Offline at event time"],
    paidAt: null,
    razorpayRef: null,
    policyId: "pol-2024-W09",
  },
];

export const MOCK_DISRUPTION_EVENTS = [
  {
    id: "evt-001",
    triggerType: "heavy_rainfall",
    triggerLabel: "Heavy Rainfall",
    city: "Mumbai",
    zone: "Andheri West",
    value: "25.4 mm/hr",
    threshold: "> 15 mm/hr",
    severity: "High",
    detectedAt: "Mar 18, 2026, 7:30 PM",
    affectedWorkers: 142,
    totalPayout: "₹45,440",
    status: "processed",
  },
  {
    id: "evt-002",
    triggerType: "severe_aqi",
    triggerLabel: "Severe AQI",
    city: "Delhi",
    zone: "Connaught Place",
    value: "AQI 342 (PM2.5)",
    threshold: "> 300 AQI",
    severity: "Hazardous",
    detectedAt: "Mar 17, 2026, 3:00 PM",
    affectedWorkers: 89,
    totalPayout: "₹33,375",
    status: "processed",
  },
  {
    id: "evt-003",
    triggerType: "flood_alert",
    triggerLabel: "Flood / Red Alert",
    city: "Chennai",
    zone: "T. Nagar",
    value: "IMD Red Alert",
    threshold: "Alert Active",
    severity: "Critical",
    detectedAt: "Mar 16, 2026, 6:00 AM",
    affectedWorkers: 211,
    totalPayout: "₹1,34,880",
    status: "processed",
  },
  {
    id: "evt-004",
    triggerType: "extreme_heat",
    triggerLabel: "Extreme Heat",
    city: "Hyderabad",
    zone: "Banjara Hills",
    value: "44.7°C feels like",
    threshold: "> 44°C",
    severity: "High",
    detectedAt: "Mar 19, 2026, 1:30 PM",
    affectedWorkers: 67,
    totalPayout: "₹21,440",
    status: "live",
  },
];

export const MOCK_INSURER_STATS = {
  totalWorkers: 8432,
  activePolicies: 3218,
  totalPayoutsThisMonth: "₹12,84,320",
  fraudFlaggedClaims: 23,
  lossRatio: 0.61,
  avgPremium: 52,
  citiesCovered: 5,
  zonesCovered: 34,
};

export const MOCK_ZONE_RISK = [
  { zone: "Andheri West", city: "Mumbai", multiplier: 1.40, riskLevel: "High" },
  { zone: "Connaught Place", city: "Delhi", multiplier: 1.30, riskLevel: "High" },
  { zone: "T. Nagar", city: "Chennai", multiplier: 1.10, riskLevel: "Medium" },
  { zone: "Koramangala", city: "Bangalore", multiplier: 1.20, riskLevel: "Medium" },
  { zone: "Banjara Hills", city: "Hyderabad", multiplier: 0.95, riskLevel: "Low" },
];

export const PREMIUM_QUOTE = {
  workerName: "Priya Murthy",
  zone: "T. Nagar, Chennai",
  avgDailyEarning: 900,
  baseRate: 35,
  zoneMultiplier: 1.10,
  weatherMultiplier: 1.00,
  historyMultiplier: 0.85,
  weeklyPremium: 32.72,
  displayPremium: 33,
  maxWeeklyCoverage: 720,
  coverageBreakdown: [
    { trigger: "Heavy Rainfall", payout: "₹360" },
    { trigger: "Extreme Heat", payout: "₹360" },
    { trigger: "Flood / Red Alert", payout: "₹720" },
    { trigger: "Severe AQI", payout: "₹450" },
    { trigger: "Curfew / Strike", payout: "₹720" },
  ],
};
